package id.thork.app.network.response.work_order


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Member(
    @Json(name = "actfinish")
    val actfinish: String,
    @Json(name = "actintlabcost")
    val actintlabcost: Double,
    @Json(name = "actintlabhrs")
    val actintlabhrs: Double,
    @Json(name = "actlabcost")
    val actlabcost: Double,
    @Json(name = "actlabhrs")
    val actlabhrs: Double,
    @Json(name = "actmatcost")
    val actmatcost: Double,
    @Json(name = "actoutlabcost")
    val actoutlabcost: Double,
    @Json(name = "actoutlabhrs")
    val actoutlabhrs: Double,
    @Json(name = "actservcost")
    val actservcost: Double,
    @Json(name = "actstart")
    val actstart: String,
    @Json(name = "acttoolcost")
    val acttoolcost: Double,
    @Json(name = "ams")
    val ams: Boolean,
    @Json(name = "aos")
    val aos: Boolean,
    @Json(name = "apptrequired")
    val apptrequired: Boolean,
    @Json(name = "assignment_collectionref")
    val assignmentCollectionref: String,
    @Json(name = "calcpriority")
    val calcpriority: Int,
    @Json(name = "changeby")
    val changeby: String,
    @Json(name = "changedate")
    val changedate: String,
    @Json(name = "chargestore")
    val chargestore: Boolean,
    @Json(name = "cxlabor")
    val cxlabor: String,
    @Json(name = "description")
    val description: String,
    @Json(name = "disabled")
    val disabled: Boolean,
    @Json(name = "doclinks")
    val doclinks: Doclinks,
    @Json(name = "downtime")
    val downtime: Boolean,
    @Json(name = "estatapprintlabcost")
    val estatapprintlabcost: Double,
    @Json(name = "estatapprintlabhrs")
    val estatapprintlabhrs: Double,
    @Json(name = "estatapprlabcost")
    val estatapprlabcost: Double,
    @Json(name = "estatapprlabhrs")
    val estatapprlabhrs: Double,
    @Json(name = "estatapprmatcost")
    val estatapprmatcost: Double,
    @Json(name = "estatapproutlabcost")
    val estatapproutlabcost: Double,
    @Json(name = "estatapproutlabhrs")
    val estatapproutlabhrs: Double,
    @Json(name = "estatapprservcost")
    val estatapprservcost: Double,
    @Json(name = "estatapprtoolcost")
    val estatapprtoolcost: Double,
    @Json(name = "estdur")
    val estdur: Double,
    @Json(name = "estintlabcost")
    val estintlabcost: Double,
    @Json(name = "estintlabhrs")
    val estintlabhrs: Double,
    @Json(name = "estlabcost")
    val estlabcost: Double,
    @Json(name = "estlabhrs")
    val estlabhrs: Double,
    @Json(name = "estmatcost")
    val estmatcost: Double,
    @Json(name = "estoutlabcost")
    val estoutlabcost: Double,
    @Json(name = "estoutlabhrs")
    val estoutlabhrs: Double,
    @Json(name = "estservcost")
    val estservcost: Double,
    @Json(name = "esttoolcost")
    val esttoolcost: Double,
    @Json(name = "firstapprstatus")
    val firstapprstatus: String,
    @Json(name = "flowactionassist")
    val flowactionassist: Boolean,
    @Json(name = "flowcontrolled")
    val flowcontrolled: Boolean,
    @Json(name = "haschildren")
    val haschildren: Boolean,
    @Json(name = "hasfollowupwork")
    val hasfollowupwork: Boolean,
    @Json(name = "historyflag")
    val historyflag: Boolean,
    @Json(name = "href")
    val href: String,
    @Json(name = "ignorediavail")
    val ignorediavail: Boolean,
    @Json(name = "ignoresrmavail")
    val ignoresrmavail: Boolean,
    @Json(name = "inctasksinsched")
    val inctasksinsched: Boolean,
    @Json(name = "interruptible")
    val interruptible: Boolean,
    @Json(name = "istask")
    val istask: Boolean,
    @Json(name = "lastcopylinkdate")
    val lastcopylinkdate: String,
    @Json(name = "lead")
    val lead: String,
    @Json(name = "lms")
    val lms: Boolean,
    @Json(name = "location")
    val location: String,
    @Json(name = "locations")
    val locations: List<Location>,
    @Json(name = "locations_collectionref")
    val locationsCollectionref: String,
    @Json(name = "longdescription")
    val longdescription: List<Longdescription>,
    @Json(name = "longdescription_collectionref")
    val longdescriptionCollectionref: String,
    @Json(name = "los")
    val los: Boolean,
    @Json(name = "matusetrans_collectionref")
    val matusetransCollectionref: String,
    @Json(name = "nestedjpinprocess")
    val nestedjpinprocess: Boolean,
    @Json(name = "newchildclass")
    val newchildclass: String,
    @Json(name = "orgid")
    val orgid: String,
    @Json(name = "outlabcost")
    val outlabcost: Double,
    @Json(name = "outmatcost")
    val outmatcost: Double,
    @Json(name = "outtoolcost")
    val outtoolcost: Double,
    @Json(name = "parentchgsstatus")
    val parentchgsstatus: Boolean,
    @Json(name = "pluscismobile")
    val pluscismobile: Boolean,
    @Json(name = "pluscloop")
    val pluscloop: Boolean,
    @Json(name = "repairlocflag")
    val repairlocflag: Boolean,
    @Json(name = "reportdate")
    val reportdate: String,
    @Json(name = "reportedby")
    val reportedby: String,
    @Json(name = "reqasstdwntime")
    val reqasstdwntime: Boolean,
    @Json(name = "respondby")
    val respondby: String,
    @Json(name = "_rowstamp")
    val rowstamp: String,
    @Json(name = "siteid")
    val siteid: String,
    @Json(name = "status")
    val status: String,
    @Json(name = "status_description")
    val statusDescription: String,
    @Json(name = "statusdate")
    val statusdate: String,
    @Json(name = "suspendflow")
    val suspendflow: Boolean,
    @Json(name = "targcompdate")
    val targcompdate: String,
    @Json(name = "targstartdate")
    val targstartdate: String,
    @Json(name = "woacceptscharges")
    val woacceptscharges: Boolean,
    @Json(name = "woclass")
    val woclass: String,
    @Json(name = "woclass_description")
    val woclassDescription: String,
    @Json(name = "wogroup")
    val wogroup: String,
    @Json(name = "woisswap")
    val woisswap: Boolean,
    @Json(name = "wonum")
    val wonum: String,
    @Json(name = "wopriority")
    val wopriority: Int,
    @Json(name = "workorderid")
    val workorderid: Int,
    @Json(name = "woserviceaddress")
    val woserviceaddress: List<Woserviceaddres>,
    @Json(name = "woserviceaddress_collectionref")
    val woserviceaddressCollectionref: String,
    @Json(name = "wostatus")
    val wostatus: List<Wostatu>,
    @Json(name = "wostatus_collectionref")
    val wostatusCollectionref: String
)