package id.thork.app.network.response.work_order


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Member(
    @Json(name = "actfinish")
    val actfinish: String? = null,
    @Json(name = "actintlabcost")
    val actintlabcost: Double? = null,
    @Json(name = "actintlabhrs")
    val actintlabhrs: Double? = null,
    @Json(name = "actlabcost")
    val actlabcost: Double? = null,
    @Json(name = "actlabhrs")
    val actlabhrs: Double? = null,
    @Json(name = "actmatcost")
    val actmatcost: Double? = null,
    @Json(name = "actoutlabcost")
    val actoutlabcost: Double? = null,
    @Json(name = "actoutlabhrs")
    val actoutlabhrs: Double? = null,
    @Json(name = "actservcost")
    val actservcost: Double? = null,
    @Json(name = "actstart")
    val actstart: String? = null,
    @Json(name = "acttoolcost")
    val acttoolcost: Double? = null,
    @Json(name = "ams")
    val ams: Boolean? = null,
    @Json(name = "aos")
    val aos: Boolean? = null,
    @Json(name = "apptrequired")
    val apptrequired: Boolean? = null,
    @Json(name = "assetnum")
    var assetnum: String? = null,
    @Json(name = "assignment")
    val assignment: List<Assignment>? = null,
    @Json(name = "assignment_collectionref")
    val assignmentCollectionref: String? = null,
    @Json(name = "availstatusdate")
    val availstatusdate: String? = null,
    @Json(name = "calcpriority")
    val calcpriority: Int? = null,
    @Json(name = "changeby")
    val changeby: String? = null,
    @Json(name = "changedate")
    val changedate: String? = null,
    @Json(name = "chargestore")
    val chargestore: Boolean? = null,
    @Json(name = "description")
    var description: String? = null,
    @Json(name = "description_longdescription")
    var descriptionLongdescription: String? = null,
    @Json(name = "disabled")
    val disabled: Boolean? = null,
    @Json(name = "djpapplied")
    val djpapplied: String? = null,
    @Json(name = "doclinks")
    val doclinks: Doclinks? = null,
    @Json(name = "downtime")
    val downtime: Boolean? = null,
    @Json(name = "estatapprintlabcost")
    val estatapprintlabcost: Double? = null,
    @Json(name = "estatapprintlabhrs")
    val estatapprintlabhrs: Double? = null,
    @Json(name = "estatapprlabcost")
    val estatapprlabcost: Double? = null,
    @Json(name = "estatapprlabhrs")
    val estatapprlabhrs: Double? = null,
    @Json(name = "estatapprmatcost")
    val estatapprmatcost: Double? = null,
    @Json(name = "estatapproutlabcost")
    val estatapproutlabcost: Double? = null,
    @Json(name = "estatapproutlabhrs")
    val estatapproutlabhrs: Double? = null,
    @Json(name = "estatapprservcost")
    val estatapprservcost: Double? = null,
    @Json(name = "estatapprtoolcost")
    val estatapprtoolcost: Double? = null,
    @Json(name = "estdur")
    var estdur: Double? = null,
    @Json(name = "estintlabcost")
    val estintlabcost: Double? = null,
    @Json(name = "estintlabhrs")
    val estintlabhrs: Double? = null,
    @Json(name = "estlabcost")
    val estlabcost: Double? = null,
    @Json(name = "estlabhrs")
    val estlabhrs: Double? = null,
    @Json(name = "estmatcost")
    val estmatcost: Double? = null,
    @Json(name = "estoutlabcost")
    val estoutlabcost: Double? = null,
    @Json(name = "estoutlabhrs")
    val estoutlabhrs: Double? = null,
    @Json(name = "estservcost")
    val estservcost: Double? = null,
    @Json(name = "esttoolcost")
    val esttoolcost: Double? = null,
    @Json(name = "failurereport_collectionref")
    val failurereportCollectionref: String? = null,
    @Json(name = "firstapprstatus")
    val firstapprstatus: String? = null,
    @Json(name = "flowactionassist")
    val flowactionassist: Boolean? = null,
    @Json(name = "flowcontrolled")
    val flowcontrolled: Boolean? = null,
    @Json(name = "haschildren")
    val haschildren: Boolean? = null,
    @Json(name = "hasfollowupwork")
    val hasfollowupwork: Boolean? = null,
    @Json(name = "historyflag")
    val historyflag: Boolean? = null,
    @Json(name = "href")
    val href: String? = null,
    @Json(name = "ignorediavail")
    val ignorediavail: Boolean? = null,
    @Json(name = "ignoresrmavail")
    val ignoresrmavail: Boolean? = null,
    @Json(name = "inctasksinsched")
    val inctasksinsched: Boolean? = null,
    @Json(name = "interruptible")
    val interruptible: Boolean? = null,
    @Json(name = "istask")
    val istask: Boolean? = null,
    @Json(name = "labtrans_collectionref")
    val labtransCollectionref: String? = null,
    @Json(name = "lastcopylinkdate")
    val lastcopylinkdate: String? = null,
    @Json(name = "lms")
    val lms: Boolean? = null,
    @Json(name = "locancestor_collectionref")
    val locancestorCollectionref: String? = null,
    @Json(name = "location")
    var location: String? = null,
    @Json(name = "locations")
    val locations: Locations? = null,
    @Json(name = "locations_collectionref")
    val locationsCollectionref: String? = null,
    @Json(name = "longdescription")
    var longdescription: List<Longdescription>? = null,
    @Json(name = "longdescription_collectionref")
    val longdescriptionCollectionref: String? = null,
    @Json(name = "los")
    val los: Boolean? = null,
    @Json(name = "matusetrans")
    var matusetrans: List<Matusetran>? = null,
    @Json(name = "matusetrans_collectionref")
    val matusetransCollectionref: String? = null,
    @Json(name = "milestone")
    val milestone: Boolean? = null,
    @Json(name = "multiassetlocci_collectionref")
    val multiassetlocciCollectionref: String? = null,
    @Json(name = "nestedjpinprocess")
    val nestedjpinprocess: Boolean? = null,
    @Json(name = "newchildclass")
    val newchildclass: String? = null,
    @Json(name = "orgid")
    val orgid: String? = null,
    @Json(name = "origrecordclass")
    var origrecordclass: String? = null,
    @Json(name = "origrecordid")
    var origrecordid: String? = null,
    @Json(name = "outlabcost")
    val outlabcost: Double? = null,
    @Json(name = "outmatcost")
    val outmatcost: Double? = null,
    @Json(name = "outtoolcost")
    val outtoolcost: Double? = null,
    @Json(name = "parentchgsstatus")
    val parentchgsstatus: Boolean? = null,
    @Json(name = "pluscismobile")
    val pluscismobile: Boolean? = null,
    @Json(name = "pluscloop")
    val pluscloop: Boolean? = null,
    @Json(name = "repairlocflag")
    val repairlocflag: Boolean? = null,
    @Json(name = "reportdate")
    var reportdate: String? = null,
    @Json(name = "reportedby")
    val reportedby: String? = null,
    @Json(name = "reqasstdwntime")
    val reqasstdwntime: Boolean? = null,
    @Json(name = "respondby")
    val respondby: String? = null,
    @Json(name = "_rowstamp")
    val rowstamp: String? = null,
    @Json(name = "schedfinish")
    val schedfinish: String? = null,
    @Json(name = "schedstart")
    val schedstart: String? = null,
    @Json(name = "siteid")
    var siteid: String? = null,
    @Json(name = "status")
    var status: String? = null,
    @Json(name = "status_description")
    val statusDescription: String? = null,
    @Json(name = "statusdate")
    val statusdate: String? = null,
    @Json(name = "storeroommtlstatus")
    val storeroommtlstatus: String? = null,
    @Json(name = "storeroommtlstatus_description")
    val storeroommtlstatusDescription: String? = null,
    @Json(name = "suspendflow")
    val suspendflow: Boolean? = null,
    @Json(name = "tooltrans_collectionref")
    val tooltransCollectionref: String? = null,
    @Json(name = "woacceptscharges")
    val woacceptscharges: Boolean? = null,
    @Json(name = "woactivity_collectionref")
    val woactivityCollectionref: String? = null,
    @Json(name = "woclass")
    val woclass: String? = null,
    @Json(name = "woclass_description")
    val woclassDescription: String? = null,
    @Json(name = "wogroup")
    val wogroup: String? = null,
    @Json(name = "woisswap")
    val woisswap: Boolean? = null,
    @Json(name = "wonum")
    val wonum: String? = null,
    @Json(name = "wopriority")
    var wopriority: Int? = null,
    @Json(name = "worklog_collectionref")
    val worklogCollectionref: String? = null,
    @Json(name = "workorderid")
    val workorderid: Int? = null,
    @Json(name = "workorderspec_collectionref")
    val workorderspecCollectionref: String? = null,
    @Json(name = "workpackmtlstatus")
    val workpackmtlstatus: String? = null,
    @Json(name = "workpackmtlstatus_description")
    val workpackmtlstatusDescription: String? = null,
    @Json(name = "worktype")
    val worktype: String? = null,
    @Json(name = "woserviceaddress")
    val woserviceaddress: List<Woserviceaddres>? = null,
    @Json(name = "woserviceaddress_collectionref")
    val woserviceaddressCollectionref: String? = null,
    @Json(name = "wostatus")
    val wostatus: List<Wostatu>? = null,
    @Json(name = "wostatus_collectionref")
    val wostatusCollectionref: String? = null,
    @Json(name = "wplabor_collectionref")
    val wplaborCollectionref: String? = null,
    @Json(name = "wpmaterial")
    var wpmaterial: List<Wpmaterial>? = null,
    @Json(name = "wpmaterial_collectionref")
    val wpmaterialCollectionref: String? = null,
    @Json(name = "wpservice_collectionref")
    val wpserviceCollectionref: String? = null,
    @Json(name = "wptool_collectionref")
    val wptoolCollectionref: String? = null,
    @Json(name = "multiassetlocci")
    val multiassetlocci: List<Multiassetlocci>? = null,
    @Json(name = "worklog")
    var worklog: List<Worklog>? = null,
    @Json(name = "woactivity")
    var woactivity: List<Woactivity>? = null,
    @Json(name = "externalrefid")
    var externalrefid: String? = null,
    @Json(name = "wplabor")
    var wplabor: List<Wplabor>? = null,
    @Json(name = "labtrans")
    val labtrans: List<Labtran>? = null,
)